version: "0.1"

services:
  electrs-testnet:
    container_name: electrs-testnet
    build: .
    ports:
      - 60001:60001
    working_dir: /
    volumes:
     - ./electrsdata:/electrsdata
     - ./electrs_config.toml:/electrs_config.toml
     - ${BITCOIN_DATA_DIR}:/root/.bitcoin
    environment:
      HOST_IP: host-gateway
    command: sh -c "ELECTRS_DAEMON_RPC_ADDR='host.docker.internal:18332' ELECTRS_DAEMON_P2P_ADDR='host.docker.internal:18333'  ELECTRS_ELECTRUM_RPC_ADDR='0.0.0.0:60001' /electrs/target/release/electrs --conf /electrs_config.toml"
    extra_hosts:
      - "host.docker.internal:host-gateway"
